config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/like/:board_id', to: 'likes#like', as: 'like'
  delete '/like/:board_id', to: 'likes#unlike', as: 'unlike'

  root 'home#index'
  resources :users, only: %i[new create edit update show] do
    get :search, on: :collection
  end
  resources :boards
  resources :comments, only: %i[create destroy]
  resources :categories, only: %i[index create destroy]
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#  user_id    :integer
#
class Like < ApplicationRecord
  belongs_to :board, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables
  before_action :logged_in_user

  def like
    unless current_user.likes.find_by(board_id: @board.id)
      like = current_user.likes.new(board_id: @board.id)
      like.save
    end
  end

  def unlike
    like = current_user.likes.find_by(board_id: @board.id)
    like.destroy 
  end

  private

  def set_variables
    @board = Board.find(params[:board_id])
    @id_name = "#like-link-#{@board.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user %>
<div id="like-link-<%= board.id %>">
  <% if @current_user.likes.find_by(board_id: board.id) %>
    <%= link_to unlike_path(board.id), method: :delete, remote: true, class: "btn btn-danger" do %>
        <%= icon "fas", "heart" %>
        <span class="badge badge-light"><%= board.likes.count %></span>
    <% end %>
  <% else %>
    <%= link_to like_path(board.id), method: :post, remote: true, class: "btn btn-outline-danger" do %>
      <%= icon "fas", "heart" %>
      <span class="badge badge-light"><%= board.likes.count %></span>
    <% end %>
  <% end %>
</div>
<% else %>
  <%= icon "fas", "heart", class: "like__logo" %> <%= board.likes.count %>
<% end %>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", board: @board  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", board: @board  )) %>');