config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/like/:board_id', to: 'likes#like', as: 'like'
  delete '/like/:board_id', to: 'likes#unlike', as: 'unlike'

  root 'home#index'
  resources :users, only: %i[new create edit update show] do
    get :search, on: :collection
  end
  resources :boards
  resources :comments, only: %i[create destroy]
  resources :categories, only: %i[index create destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @boards = Board.order('updated_at DESC').limit(5)
    @popular_boards = Board.order('likes_count DESC').limit(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide(:title, '掲示板') %>

<div class="top__items">
  <h1>ホーム</h1>
  <div class="ml-auto boards__linkBox">
    <% if current_user %>
      <%= link_to "掲示板一覧", boards_path, class: "btn btn-outline-primary" %>
      <%= link_to "新規作成", new_board_path, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to new_user_path, class: "btn btn-outline-primary" do %>
        <%= icon "fas", "sign-in-alt" %> 新規登録
      <% end %>
      <%= link_to "ログイン", login_path, class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

<h4>新着掲示板</h4>
<%= render partial: 'layouts/boards_list', locals: { boards: @boards } %>
<div class="home__moreWrap">
<%= link_to 'もっと見る', boards_path, class: "home__more" %>
</div>

<h4 class="home__popularityTitle">人気の投稿</h4>
<%= render partial: 'layouts/boards_list', locals: { boards: @popular_boards } %>