config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/like/:board_id', to: 'likes#like', as: 'like'
  delete '/like/:board_id', to: 'likes#unlike', as: 'unlike'

  root 'home#index'
  resources :users, only: %i[new create edit update show] do
    get :search, on: :collection
  end
  resources :boards
  resources :comments, only: %i[create destroy]
  resources :categories, only: %i[index create destroy]
end

app/views/layouts/_boards_list.html.erb
<table class="table table-hover boards__table">
  <tbody>
    <% boards.each do |board| %>
      <tr>
        <th>
          <%= link_to image_tag(board.user.image.thumb1.url, class: 'trim-image-to-circle'), board.user %>
        </th>
        <td class="phone__size"><%= link_to board.title.truncate(25), board, class: "board__listTitle" %>
        <br><% board.categories.each do |cate| %>
              <span><%= link_to cate.name, boards_path(category_id: cate.id), class: "badge badge-primary phone__size" %></span>
            <% end %>
        </td>
        <td class="phone__size"><%= link_to board.user.user_name.truncate(6), board.user, class: "board__listTitle" %></td>
        <td class="tab__invisible"><%= board.updated_at.to_s(:datetime_jp) %>更新</td>
        <td class="tab__invisible"><%= link_to '詳細', board, class: "btn btn-outline-success" %></td>
        <td class="phone__size"><%= render 'likes/like', board: board %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_error_messages.html.erb
<% if flash[:error_messages] %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy;掲示板 | 
    <% if @current_user %>
      <%= link_to 'マイページ', @current_user %>
      <%= link_to 'ログアウト', logout_path, method: :delete %>
    <% else %>
      <%= link_to '新規登録', new_user_path %>
      <%= link_to 'ログイン', login_path %>
    <% end %>
  </p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg__header">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="scale__title" ontouchstart="">
    <h4 class="header__title"><%= icon "fas", "chalkboard" %> 掲示板</h4>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= header_link_item('ホーム', root_path) %>
      </li>
      <li class="nav-item">
        <%= header_link_item('掲示板一覧', boards_path) %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= header_link_item("カテゴリー一覧", categories_path) %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
          <% if @current_user %>
            <%= link_to 'マイページ', @current_user, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
          <% else %>
            <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
            <%= link_to 'ログイン', login_path, class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    <%= form_with url: search_users_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0' do |f| %>
      <%= f.text_field :user_name, class: 'form-control mr-sm-2', placeholder: "ユーザー検索" %>
      <%= f.submit "\uf002 検索", class: 'btn btn-primary my-2 my-sm-0 fas search__submit' %>
    <% end %>
  </div>
</nav>

app/views/layouts/_must_badge.html.erb
<span class="badge badge-danger">必須</span>

app/views/layouts/_notice_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>